### ISSUE TITLE
Nuvla v2.0 api-server critical requirements

### ISSUE THREAD

**Issue by mebster** [nuvla/api-server#128]
API Server:

 - [x] nuvla/api-server#36: use kebab-case for resource attributes
 - [x] nuvla/api-server#35: simplify internal authentication map (better if done with nuvla/server#29)
 - [x] nuvla/api-server#34: simplify resource metadata schema
 - [x] nuvla/api-server#119: verify resource metadata
 - [x] nuvla/api-server#33: refactor resource lifecycle testing
 - [x] nuvla/api-server#32: move to ES REST API
 - [x] nuvla/api-server#30: user refactoring
 - [x] nuvla/api-server#29: change ACL implementation

Moved to later releases:
 - nuvla/api-server#31: provide bulk delete (depends on nuvla/api-server#29)
