### ISSUE TITLE
[EPIC] implement remote SSH mechanism for NuvlaBox

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#362]
according to the proposal in https://github.com/nuvla/api-server/issues/335#issuecomment-635881719:

 - [x] implement new SSH credential type in Nuvla (https://github.com/nuvla/api-server/issues/356)
 - [x] add new credential creation to UI (https://github.com/nuvla/ui/issues/377)
 - [x] add new option to NB creation workflow, to handle the NB SSH key (https://github.com/nuvla/ui/issues/378)
 - [x] add NUVLABOX_SSH_PUB_KEY env var to mgmt-api component (https://github.com/nuvlabox/management-api/issues/2)
 - [x] add new ssh-keys attribute for NuvlaBox resource (https://github.com/nuvla/api-server/issues/357)
 - [x] change USB self-registration accordingly to match the new trigger file content (https://github.com/nuvla/ui/issues/385)
 - [x] add list of ssh keys to NuvlaBox edge detail UI page (https://github.com/nuvla/ui/issues/379)
 - [x] add new SSH-specific actions to NuvlaBox resource (https://github.com/nuvla/api-server/issues/358 and https://github.com/nuvla/api-server/issues/359)
 - [x] add new SSH management api calls to mgmt-api (https://github.com/nuvlabox/management-api/issues/3)
 - [x] document (https://github.com/nuvla/documentation/issues/46)
